fabstei_shorturl_url:
    path:  /url-manager
    defaults: { _controller: FabsteiShorturlBundle:Url:indexAction }

fabstei_shorturl_url_new:
    path:  /url-manager/new
    defaults: { _controller: FabsteiShorturlBundle:Url:newAction }

fabstei_shorturl_url_show:
    path:  /url-manager/show/{id}
    defaults: { _controller: FabsteiShorturlBundle:Url:showAction }

fabstei_shorturl_url_create:
    path:  /url-manager/create
    defaults: { _controller: FabsteiShorturlBundle:Url:createAction }
    requirements:
        _method:  POST

fabstei_shorturl_url_update:
    path:  /url-manager/update/{id}
    defaults: { _controller: FabsteiShorturlBundle:Url:updateAction }
    requirements:
        _method:  POST

fabstei_shorturl_url_delete:
    path:  /url-manager/delete/{id}
    defaults: { _controller: FabsteiShorturlBundle:Url:deleteAction }

fabstei_shorturl_url_edit:
    path:  /url-manager/edit/{id}
    defaults: { _controller: FabsteiShorturlBundle:Url:editAction }
