language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - SYMFONY_VERSION=3.4.*

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: phpunit --coverage-clover "clover"

notifications:
    email:
        - soefelix@gmail.com
